### ISSUE TITLE
Cannot run it on ESP32 WiFi_AP mode

### ISSUE THREAD

**Issue by MkLHX** [ayushsharma82/ElegantOTA#1]
Hi there!

Thanks for this promising lib but in my case, i need to do ota through async web server and on AP mode only.
No wifi STA enabled on ESP32.
And in header we can see only ESP8266 management. So can we use it on ESP32?

**Comment by ayushsharma82** [comment]
ESP32's default Webserver Library doesn't work while sending webpages by using `send_P` function.
I am in progress of making a Version of ElegantOTA based on AsyncWebServer.

I will notify you on this issue when it's done.

**Comment by ayushsharma82** [comment]
Hi, Just Released AsyncElegantOTA, It works with both ESP8266 and ESP32.  Checkout at https://github.com/ayushsharma82/AsyncElegantOTA
