### ISSUE TITLE
Can elegantota update over BT?

### ISSUE THREAD

**Issue by skysingh** [ayushsharma82/ElegantOTA#105]
My clients do not want their device to connect over wifi to their network. They want to connect over BT (classic or BLE) to their Android phone which in turn is connected to the internet. Then download the binary and squirt it in to the esp32 for ota. Is this feasible ? Willing to pay ?

**Comment by ayushsharma82** [comment]
@skysingh Nope, that's not possible.

**Comment by awong1900** [comment]
BLE is too slower for OTA.  I have same though, but i delete it.  You can use BLE update SSID and PWR to device, then ota with internet.
