### ISSUE TITLE
Erase Wifi configuration before restart

### ISSUE THREAD

**Issue by Daryavahus** [ayushsharma82/ElegantOTA#112]
I added  to library code:
ESP.eraseConfig() before ESP.restart().
I've noticed, that when Wifi configuration is not  erased, when firmware is stored in flash memory, I had errors and ESP crashed.
After that  alll Wifi errors (like pm_send_nullfunc), are gone away.

**Comment by ayushsharma82** [comment]
For anyone with same requirement, now you can use the `onEnd` callback provided with V3 of ElegantOTA for running business logic before reboot.
