### ISSUE TITLE
Elegant OTA by URL

### ISSUE THREAD

**Issue by MikeF5J** [ayushsharma82/ElegantOTA#114]
Ayush,
The ElegantOTA works well.  I would like to try and simplify the call to the device and do the FW update through an auto created URL.

Can you assist by helping with such a URL construct?
e.g.
ip/update/ x??x "fw filename & path" + button submitted

By sending the URL to the browser the IP should be started and the fw file selected and added and start the OTA automatically.

The coffees I'll save I'll pass to you.

Thank you
Mike

**Comment by robertobuti** [comment]
Hello,
me too, i like same. OTA updated version working with a cloud storage coudl be a great idea.

**Comment by awong1900** [comment]
I like this idea. I mange firmware on the S3, so if can from link to ota, it is fantastic.

**Comment by ayushsharma82** [comment]
Not planned for ElegantOTA. The logic to do that is completely different from what ElegantOTA was originally designed for; which is  - a simple OTA webpage.
