### ISSUE TITLE
Add "Home" button upon successful update

### ISSUE THREAD

**Issue by rodneygmorgan** [ayushsharma82/ElegantOTA#115]
This is not an issue, but a simple enhancement request.  Upon successful upload the user is prompted with a "Back" button which returns to the inital ElegantOTA page.  I believe an additional button to take the user to the root page would be useful.  Short of modifying the URL in the address bar, the user has no mechanism to return the device's home page.

**Comment by adampoconnor** [comment]
+1 on this. This would be great for our purposes too. Even better yet, a callback in the code to define the button text and URL would really make this powerful.

**Comment by Tsjippy** [comment]
+1
