### ISSUE TITLE
[v3] Wrong callback parameter value for success

### ISSUE THREAD

**Issue by mathieucarbou** [ayushsharma82/ElegantOTA#119]
It should be: `if (postUpdateCallback != NULL) postUpdateCallback(!Update.hasError());`

**Comment by ayushsharma82** [comment]
Fixed with this commit: https://github.com/ayushsharma82/ElegantOTA/commit/d0635c76c0925b7f21caf36fe9a3f3dbd85775de

Thanks for reporting it.
