### ISSUE TITLE
[v3] auto reboot flag to allow to control the reboot

### ISSUE THREAD

**Issue by mathieucarbou** [ayushsharma82/ElegantOTA#120]
`void setAutoReboot(bool auto_reboot) { _auto_reboot = auto_reboot; };`

then use `_auto_reboot` to skip the loop and timer, to let the callback responsible to handle the restart

**Comment by ayushsharma82** [comment]
Implemented with https://github.com/ayushsharma82/ElegantOTA/commit/e9204cf0e1533c946be3637bacafe433df5b8a67
