### ISSUE TITLE
[v3] do not activate debug mode by default

### ISSUE THREAD

**Issue by mathieucarbou** [ayushsharma82/ElegantOTA#125]
`#define UPDATE_DEBUG 1` => should be removed from the header file and not set to 1 by default. The naming could easily conflict with some other headers

`#define ELEGANTOTA_DEBUG 1` => should not be set to ` by default.

I have changed to:

```c
// #define ELEGANTOTA_DEBUG 1
// #define UPDATE_DEBUG 1

#ifdef ELEGANTOTA_DEBUG // instead of #if ELEGANTOTA_DEBUG
```

So that I can use in platformio:

```
[env:debug]
build_type = debug
build_flags = ${env.build_flags}
  -O0
  -ggdb -ggdb3 -g3
  -D DEBUG
  -D ENABLE_DEBUG
  -D ELEGANTOTA_DEBUG
  -D CORE_DEBUG_LEVEL=3
```

**Comment by ayushsharma82** [comment]
Instead I've wrapped them with `#ifndef` to set default to `0` - https://github.com/ayushsharma82/ElegantOTA/commit/c08acad0b42fd0bbc138cbd97b353c7650ea8ddc
