### ISSUE TITLE
Uploading the SPIFFS via OTA does not work

### ISSUE THREAD

**Issue by nightflyer88** [ayushsharma82/ElegantOTA#13]
I have a spiffs *.bin file that I want to upload via elegantOTA, but an error occurs: 

OTA Failed
Reason - Update error: ERROR[10]: Magic byte is wrong, not 0xE9

**Comment by ayushsharma82** [comment]
Make sure your SPIFFS .bin file contains `.spiffs.` in the name before uploading to ElegantOTA.

**Comment by ayushsharma82** [comment]
Added a selection radio buttons with V2.
