### ISSUE TITLE
[v3] Enlarge settingsContent width

### ISSUE THREAD

**Issue by mathieucarbou** [ayushsharma82/ElegantOTA#131]
When entering a version or hardware id which is too long, the text is wrapping, which does not look very nice ;-)
I would suggest to increase the width from

`<div id="settingsContent" class="flex flex-col gap-4 mt-6 w-[300px]">`
![image](https://github.com/ayushsharma82/ElegantOTA/assets/61346/8d2622e6-871f-4bd7-8a89-e7d2a45a3902)

to

`<div id="settingsContent" class="flex flex-col gap-4 mt-6 w-[400px]">`
![image](https://github.com/ayushsharma82/ElegantOTA/assets/61346/20dfb0c2-a501-4649-be21-c0711fafec46)

I am not a CSS expert: ideally, the settingsContent would not need to be of fixed size and should resize based on the content until a maximum width. But I don't know how to do that ;-)

**Comment by ayushsharma82** [comment]
@mathieucarbou , report bugs/feature requests of pro version to my support mail ( support@softt.io ) only :) People often mix up things, so it's better to keep things separate.

I'll look into making the column responsive so that on PCs it has a greater width.

**Comment by mathieucarbou** [comment]
thanks!
