### ISSUE TITLE
[v3] Wrong platforms when using lib_compat_mode = strict and lib_ldf_mode = deep+

### ISSUE THREAD

**Issue by mathieucarbou** [ayushsharma82/ElegantOTA#132]
Once need to change to `"platforms": ["espressif8266", "espressif32", "raspberrypi"]` in `library.json` to be compatible with:
```
lib_compat_mode = strict
lib_ldf_mode = deep+
```

**Comment by ayushsharma82** [comment]
Fixed with https://github.com/ayushsharma82/ElegantOTA/commit/fe88d21402fb72116705540ed8ebc9f53acc369c
