### ISSUE TITLE
AsyncWebserver

### ISSUE THREAD

**Issue by nozbey** [ayushsharma82/ElegantOTA#134]
Hello, 

in esp32 AsyncWebserver not accepted because default 

```
#ifndef ELEGANTOTA_USE_ASYNC_WEBSERVER
  #define ELEGANTOTA_USE_ASYNC_WEBSERVER 1
#endif
```

am ı need to change AsyncWebserver to Webserver ? or change default value of ELEGANTOTA_USE_ASYNC_WEBSERVER ?? 

thanks,
nuri

**Comment by ayushsharma82** [comment]
If you change the default to 1 and recompile your code, it should use
AsyncWebServer.
