### ISSUE TITLE
Compatibility issues with AsyncWebServer installed thru library manager

### ISSUE THREAD

**Issue by Augustinas01** [ayushsharma82/ElegantOTA#135]
When i include <AsyncElegantOTA.h> then it won't compile and I get 
![image](https://github.com/ayushsharma82/ElegantOTA/assets/75675532/4fd9a738-48d6-4b67-9716-a98dbb6578f5)
Here are my includes
![image](https://github.com/ayushsharma82/ElegantOTA/assets/75675532/3def64f5-70bd-411d-b925-12bef3201849)
I'm using Arduino IDE, libraries installed thru library manager

**Comment by Augustinas01** [comment]
I been able to compile it successfully by pulling ESPAsyncWebServer from git, then it gave me errors not finding methods in ElegantOTA, so I changed lib by deleting all chip checking and declaring ELEGANTOTA_USE_ASYNC_WEBSERVER 1 inside lib, now let's hope it's actually working.

**Comment by ayushsharma82** [comment]
I noticed your included library is different than what ElegantOTA uses.
Please use the official ESPAsyncWebserver library instead of forks.
