### ISSUE TITLE
on Examples AsyncDemo error

### ISSUE THREAD

**Issue by anwfeb** [ayushsharma82/ElegantOTA#139]
AsyncDemo:88:20: error: cannot convert 'AsyncWebServer*' to 'ESP8266WebServer*' {aka 'esp8266webserver::ESP8266WebServerTemplate<WiFiServer>*'}
   88 |   ElegantOTA.begin(&server);    // Start ElegantOTA
      |                                     ^~~~~~~
      |                                     |
      |                                    AsyncWebServer*

**Comment by ScruffR** [comment]
I got a similar issue with ESP32
```tet
error: no matching function for call to 'ElegantOTAClass::begin(AsyncWebServer*)'
   ElegantOTA.begin(&server);

note: candidate: 'void ElegantOTAClass::begin(WebServer*, const char*, const char*)'
     void begin(ELEGANTOTA_WEBSERVER *server, const char * username = "", const char * password = "");

note:   no known conversion for argument 1 from 'AsyncWebServer*' to 'WebServer*'
```

**Comment by bmgmo-iscteiulpt** [comment]
I got the exact same error, cant figure out how to fix it :/

**Comment by ayushsharma82** [comment]
Did you guys enable Async Mode as per docs before compiling the example?

**Comment by bmgmo-iscteiulpt** [comment]
Yes, but same error

**Comment by ayushsharma82** [comment]
Weird, CI gave it a pass. I'll need the following details to further diagnose it:

1. Are you using Arduino IDE or PlatformIO?
2. Which MCU are you using?
3. Board/Platform version of your microcontroller

**Comment by bmgmo-iscteiulpt** [comment]
Arduino IDE
Its an Expressif ESP32-s2 wrover
The version I'm not sure how to get it 

![20231101_174810](https://github.com/ayushsharma82/ElegantOTA/assets/32707046/9779e392-7fc3-4cc7-ac85-b3ecbd30e712)

**Comment by bmgmo-iscteiulpt** [comment]
When the Async mode is set on the library file, it gives the following errors

![erger](https://github.com/ayushsharma82/ElegantOTA/assets/32707046/f10e24ea-010d-4844-a007-01867e9de76c)

**Comment by ayushsharma82** [comment]
@bmgmo-iscteiulpt This is a different error compared to what  this issue was initially created for.

You can fix it by downgrading to a stable "arduino-esp32" release in Board Manager. Currently you are using v3.0.0-alphav2 which is not stable.

**Comment by bmgmo-iscteiulpt** [comment]
worked! didnt even noticed the alpha version when installed the boards .. thank you!

**Comment by ScruffR** [comment]
For an older project had it enabled but forgot to do that again after a library update cycle overrode that 😳

**Comment by ayushsharma82** [comment]
@ScruffR  Yeah that's inevitable with Arduino IDE. I'll suggest moving to PlatformIO [with this approach](https://docs.elegantota.pro/async-mode/#for-platformio) so that the async flag is persisted within the project itself. One time learning effort, PIO offers a better experience in terms of compile time etc once you are familiar with it.

**Comment by ayushsharma82** [comment]
@anwfeb Status update on your issue? If it was resolved, please close the issue.

**Comment by Luckas007666** [comment]
@ayushsharma82 : Please also have a look at issue #141 . The issue itself is solved, but with a manual fix - maybe this can be added by you to the original ? https://github.com/ayushsharma82/ElegantOTA/issues/141#issuecomment-1808890201

**Comment by HARIS4820** [comment]
![Screenshot from 2024-06-27 05-48-25](https://github.com/ayushsharma82/ElegantOTA/assets/68471641/08985b47-e300-473c-8a86-36f91631954c)
