### ISSUE TITLE
Add update mode to callbacks

### ISSUE THREAD

**Issue by mistic100** [ayushsharma82/ElegantOTA#140]
Hi

`onEnd` particularly would benefit to know which update (firmware or fs) was completed.

**Comment by ayushsharma82** [comment]
Good Suggestion. I'll add that in future release.

**Comment by ayushsharma82** [comment]
Added with V3.

**Comment by mistic100** [comment]
Not stale

**Comment by ayushsharma82** [comment]
@mistic100  Good idea, I'll implement your approach.
