### ISSUE TITLE
Error in AsyncDemo 

### ISSUE THREAD

**Issue by Nikitanagar** [ayushsharma82/ElegantOTA#141]
AsyncTCP.h and ESPAsyncWebServer.h files are not found. Can you let me know the solution?

**Comment by Luckas007666** [comment]
when adding 
` "dependencies": { 
    "ottowinter/ESPAsyncWebServer-esphome": "^2.1.0",
    "ottowinter/ESPAsyncTCP-esphome": "1.2.3"
  },`

to library.json file of ElegantOTA, it compiles fine

**Comment by Nikitanagar** [comment]
Thank you for the response Luckas, 
Yeah, This error has been solved after adding the above lines in library.json. But another error is found _**_argument of type "Asyncwebserver *"  is incompatible with parameter of type  "Webserver *"_**_

**Comment by Luckas007666** [comment]
Did you enable Async Mode ?  https://docs.elegantota.pro/async-mode/#for-platformio

**Comment by Nikitanagar** [comment]
Thank you it is working fine.
