### ISSUE TITLE
File2Raw Utility Error

### ISSUE THREAD

**Issue by t-jones14** [ayushsharma82/ElegantOTA#142]
File2Raw utility as outlined in ElegantOTAPro documentation is broken. Unable to access.

![image](https://github.com/ayushsharma82/ElegantOTA/assets/40005961/a28e78c0-8dd3-4843-9949-380adb9d7708)

**Comment by ayushsharma82** [comment]
File2Raw actually runs on my lab server and there is an internet connectivity issue going on in our area. It should be fixed in a day or two automatically.

**Comment by t-jones14** [comment]
Thank you. Do you have alternate utility you would recommend by chance?

**Comment by ayushsharma82** [comment]
File2Raw is the only recommended utility. You can keep trying again in a few minutes, it's just the fiber line which is acting up here.

**Comment by ayushsharma82** [comment]
Connectivity issue was resolved a few days ago and File2Raw is online. Closing this issue.
