### ISSUE TITLE
AMB82-MINI didn't work with OTA

### ISSUE THREAD

**Issue by rkuo2000** [ayushsharma82/ElegantOTA#150]
I compile ElegantOTA AsynDemo.ino for AMB82-MINI (RTL8735B EVB with Camera), but it failed to compile.
**AMB82-MINI** : https://www.amebaiot.com/en/amebapro2-amb82-mini-arduino-getting-started/

Error Messages: 
In file included from C:\Users\rkuo2\AppData\Local\Temp\.arduinoIDE-unsaved20231112-9220-7cqffu.heusb\Async_Demo\Async_Demo.ino:15:
d:\Users\rkuo2\Documents\Arduino\libraries\AsyncTCP\src/AsyncTCP.h:26:10: fatal error: sdkconfig.h: No such file or directory
   26 | #include "sdkconfig.h"
      |          ^~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: exit status 1

**Comment by ayushsharma82** [comment]
@rkuo2000 ElegantOTA only supports ESP8266, ESP32 & RP2040 at the moment. I'll try to add support for your MCU.
