### ISSUE TITLE
Timeout if OTA fails

### ISSUE THREAD

**Issue by peter3099** [ayushsharma82/ElegantOTA#161]
Hello 

I just wanted to start thanking you for this library, is great and really well done.

I just moved from the old deprecated to the new one.

I bought the Pro 😎, totally worth it!

One thing I noticed is that if the update fails sometimes I don't get the onEnd call back.

So I try 2 things, one was I corrupted a bin files by erasing some lines and the other one was by closing the browser window in the middle of the update, and I get this
![image](https://github.com/ayushsharma82/ElegantOTA/assets/22412633/e76552cd-b248-45a0-901a-a808705bf02c)

The last line is being printed because of this if in the main loop
<img width="454" alt="image" src="https://github.com/ayushsharma82/ElegantOTA/assets/22412633/338203d2-904d-4b26-b14a-157b88935c66">

If don't put this I see that the device will never restart and it will stay in that state for ever, some times it is not responsive at all. I was thinking that it might be a good idea to add an optional timeout from the time the OTA process starts. 

In my use case OTA is usually disable until I enable it via web server. 

Just an idea, thoughts?

Thanks again 
regards

**Comment by ayushsharma82** [comment]
Hi @peter3099 

Thanks for your purchase and sharing pleasant feedback.


This seems like a network issue in which packets are being dropped. Let me know if you get the same result when your ESP has 100% WiFi strength.

Happy to implement a timeout logic but best to figure out the core issue first.
