### ISSUE TITLE
ElegantOTA over ethernet on ESP32

### ISSUE THREAD

**Issue by Sejny** [ayushsharma82/ElegantOTA#166]
Is tested with ESP32 connected over ethernet?  I dont see any handling with watchdog timeouts.  This problem occur in previous Async ElegantOTA, see issue:   https://github.com/ayushsharma82/AsyncElegantOTA/issues/33

**Comment by mathieucarbou** [comment]
No issue with the big project I am working on (https://yasolr.carbou.me).

tested with wt32-eth1:
- in ap mode (no ethernet cable)
- with ethernet cable
- esp32 nodemcu devkit in ap mode

my firmware is quite big. here's my partition table fyi:

```
# Name,   Type, SubType, Offset,   Size,    Flags
nvs,      data, nvs,     0x9000,   0x5000,
otadata,  data, ota,     0xe000,   0x2000,
app0,     app,  ota_0,   0x10000,  0x1F0000,
app1,     app,  ota_1,   0x200000, 0x1F0000,
spiffs,   data, spiffs,  0x3F0000, 0x10000,
```

No watchdog triggered.

I am on ESP32 dual core.

The async_task (AsyncTCP) is running on core 1 by default.

I guess this issue relates to single core devices ?
