### ISSUE TITLE
where is the buffer image locate in flash mem?

### ISSUE THREAD

**Issue by coyool** [ayushsharma82/ElegantOTA#17]
where is the buffer image locate in flash mem? 
or I want to know how to make my bin file fix to the limition when I use thi lib? just as the arduino manual say?

**Comment by ayushsharma82** [comment]
Hi,
It's written directly to the OTA partition which is created when you select the flash size in options of Arduino IDE. There is no buffer in the HTTP layer.

To make the SPIFFS .bin file:
1. Install this tool: https://github.com/esp8266/arduino-esp8266fs-plugin#installation
2. Generate file like this: https://github.com/esp8266/arduino-esp8266fs-plugin#usage
