### ISSUE TITLE
Update successful, but no reboot

### ISSUE THREAD

**Issue by dalepa** [ayushsharma82/ElegantOTA#171]
The update works fine, but no reboot after the update.   A power cycle is required which isn't great when you need to do it remotely

Firebeetle 2 ESP32-E Gravity IO Shield 

suggestions?

**Comment by mathieucarbou** [comment]
- did you set `setAutoReboot (true)` ?
- do you call `ElegantOTA.loop()` in your loop ?
- did you register a `ElegantOTA.onEnd()` callback to display the result of the Update ? If the callback returns `false`, then you know the update has errors and ESP won't restart.
