### ISSUE TITLE
ElegantOTA crashed on ESP32 NINA-W102 EVK

### ISSUE THREAD

**Issue by pberna67** [ayushsharma82/ElegantOTA#174]
Dear Developer

I'm trying to use the Demo project available in Elegant OTA lib as it is (only Wifi password/ SSID has been updated)
Hardware; EVK NNA-W10
Lib ESP32 Espressif System version 2.0.14 installed

![image](https://github.com/ayushsharma82/ElegantOTA/assets/17097864/043f6962-86f8-4bd4-a7e2-24d2af7abb0b)

When I try to download the binary image of firmware, using Elegant OTA web interface, I see that the CPU crashes:

22:37:02.529 -> ets Jul 29 2019 12:21:46
22:37:02.529 -> 
22:37:02.529 -> rst:0x1 (POWERON_RESET),boot:0x37 (SPI_FAST_FLASH_BOOT)
22:37:02.529 -> configsip: 0, SPIWP:0xee
22:37:02.529 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
22:37:02.529 -> mode:DIO, clock div:1
22:37:02.529 -> load:0x3fff0030,len:1184
22:37:02.529 -> load:0x40078000,len:13260
22:37:02.529 -> load:0x40080400,len:3028
22:37:02.529 -> entry 0x400805e4
22:37:02.957 -> 
22:37:03.482 -> ...
22:37:04.469 -> Connected to WIND-WiFi-C69F
22:37:04.469 -> IP address: 192.168.10.179
22:37:04.469 -> HTTP server started
22:37:24.930 -> OTA update started!
22:37:24.977 -> Update Received: Nella_3.ino.nina_w10.bin
22:37:24.977 -> OTA Progress Current: 1436 bytes, Final: 0 bytes
22:37:24.977 -> 
22:37:24.977 -> abort() was called at PC 0x40081e96 on core 1
22:37:24.977 -> 
22:37:24.977 -> 
22:37:24.977 -> Backtrace: 0x4008366d:0x3ffb1d90 0x4008bc59:0x3ffb1db0 0x40090fd1:0x3ffb1dd0 0x40081e96:0x3ffb1e50 0x400dfe73:0x3ffb1ea0 0x400d9be1:0x3ffb1ec0 0x400d97af:0x3ffb1ee0 0x400d9929:0x3ffb1f00 0x400d8d52:0x3ffb1f30 0x400d8553:0x3ffb1f80 0x400d8592:0x3ffb1fa0 0x400d4806:0x3ffb1fe0 0x400d54c5:0x3ffb2020 0x400d6205:0x3ffb2120 0x400d87e2:0x3ffb2220 0x400d2b36:0x3ffb2270 0x400db245:0x3ffb2290
22:37:25.024 -> 
22:37:25.024 -> 
22:37:25.024 -> 
22:37:25.024 -> 
22:37:25.024 -> ELF file SHA256: ce969ac3041109a3
22:37:25.024 -> 
22:37:25.260 -> Rebooting...
22:37:25.260 -> ets Jul 29 2019 12:21:46
22:37:25.260 -> 
22:37:25.260 -> rst:0xc (SW_CPU_RESET),boot:0x37 (SPI_FAST_FLASH_BOOT)
22:37:25.260 -> configsip: 0, SPIWP:0xee
22:37:25.260 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
22:37:25.306 -> mode:DIO, clock div:1
22:37:25.306 -> load:0x3fff0030,len:1184
22:37:25.306 -> load:0x40078000,len:13260
22:37:25.306 -> load:0x40080400,len:3028
22:37:25.306 -> entry 0x400805e4
22:37:25.731 -> 
22:37:26.251 -> ...
22:37:27.242 -> Connected to WIND-WiFi-C69F
22:37:27.242 -> IP address: 192.168.10.179
22:37:27.242 -> HTTP server started

Anyone can confirm the problem with Lib ESP32 Espressif System version 2.0.14 installed  ?

Thanks 
Paolo

**Comment by mathieucarbou** [comment]
@pberna67 : FYI, you stack trace is useless (and depends on your compiled firmware). Please unscramble it, or use https://maximeborges.github.io/esp-stacktrace-decoder/ to do so next time.
