### ISSUE TITLE
Documentation fails to mention how to access portal

### ISSUE THREAD

**Issue by chloehassall27** [ayushsharma82/ElegantOTA#175]
Somehow I cannot find anywhere in the documentation or examples the actual route to access the portal page... I figured out that it was just at /upload, but it should be a bit more obvious.

**Comment by MikeCley** [comment]
Nice web site, neat library for update and there no mention of how to do update or /update path in documentation. Its very strange.

**Comment by ayushsharma82** [comment]
Done. Thanks for the suggestion 👍🏻 ( Ref: https://docs.elegantota.pro/getting-started/#final-code )
