### ISSUE TITLE
I want to purchase The Elegant ETA Pro but I have Questions.

### ISSUE THREAD

**Issue by Ugobyte** [ayushsharma82/ElegantOTA#180]
(I posted this in 'Discussions' but Ill also post here, since 'Issues' get's more attention)

I already implemented Elegant OTA in my ESP32-S3 project and it works great.
I want to buy the Pro version . I have questions before i buy it.

Will there be new files? .h, .cpp, .html etc?
How will it affect the one I already have now?
Do i have to do rewrite the entire code I already wrote with the free Elegant OTA that I'm using now?
How do I add my company's logo?

**Comment by ayushsharma82** [comment]
Hi @Ugobyte ,

Thanks for your interest in ElegantOTA Pro.

> Will there be new files? .h, .cpp, .html etc?

Yes, you will be provided with whole library and UI source code.

> How will it affect the one I already have now? Do i have to do rewrite the entire code I already wrote with the free Elegant OTA that I'm using now?

No rewrite is necessary. You just have to replace `ElegantOTA` with `ElegantOTAPro`. Pro version builds on top of lite version so everything can be ported without much effort.

> How do I add my company's logo?

Documentation for pro and lite version is hosted on the same website. Ref: https://docs.elegantota.pro/branding/

**Please note:** Discussions and Issues are used for community interaction only. For any further queries please use the dedicated communication channels. Ref: https://elegantota.pro/contact-us
