### ISSUE TITLE
ElegantOTA PlatformIO error

### ISSUE THREAD

**Issue by Bredahl** [ayushsharma82/ElegantOTA#206]
I get these two error messages,
with query parameters

a value of type "const AsyncWebParameter *" cannot be used to initialize an entity of type "AsyncWebParameter *"
invalid conversion from 'const AsyncWebParameter*' to 'AsyncWebParameter*' [-fpermissive]

when I use this code in Platform IO

   server.on("/itvl", HTTP_GET, [](AsyncWebServerRequest *request){
    int paramsNr = request->params();
    Serial.println(paramsNr);
 
    for(int i=0;i<paramsNr;i++){
         
        AsyncWebParameter* p = request->getParam(i);
        Serial.print("Param name: ");
        Serial.println(p->name());
        Serial.print("Param value: ");
        Serial.println(p->value());
        Serial.println("------");
    }
     
    request->send(200, "text/plain", "message received");
  });

**Comment by ayushsharma82** [comment]
This is not related to ElegantOTA.

**Comment by Bredahl** [comment]
No, but it is related to those libraries
you recommend AsyncTCP

**Comment by Bredahl** [comment]
for Esp32
(mathieucarbou) [AsyncTCP](https://github.com/mathieucarbou/AsyncTCP#v3.1.4) @ v3.1.4
(mathieucarbou) [ESPAsyncWebServer](https://github.com/mathieucarbou/ESPAsyncWebServer#v3.0.5) - v3.0.5

**Comment by ayushsharma82** [comment]
Then please open the issue in repo for dependencies. Mathieu will help you, those forks are not maintained by me.

**Comment by mathieucarbou** [comment]
@Bredahl : the api was fixed. The object is not mutable so you need to use const. The api enforces that now 

'const AsyncWebParameter* p = request->getParam(i);'

**Comment by Bredahl** [comment]
thank you very much.
That's what made it work!!
