### ISSUE TITLE
ESP-Home incompatibility

### ISSUE THREAD

**Issue by k4lls** [ayushsharma82/ElegantOTA#211]
I have a project with esphome/AsyncTCP-esphome@2.1.3 and ottowinter/ESPAsyncWebServer-esphome @ ^3.2.2.
I can't use ElegantOTA with these library since you are using mathieu carbou's library. Sadly they are not fully compatible. Is there a way to allow the use of different library ?

**Comment by mathieucarbou** [comment]
They are: our fork is based on ESPhome 's one.
Please open an issue in the relevant projet and show your compile issue I will have a look to help.
It is also possible that you are using deprecated methods for esp8266 in your code.

**Comment by ayushsharma82** [comment]
@k4lls Just added with v3.1.4 - https://docs.elegantota.pro/async-mode/#use-of-unrecommended-dependencies-experimental
