### ISSUE TITLE
Autoreboot

### ISSUE THREAD

**Issue by petr-novak-digibrocz** [ayushsharma82/ElegantOTA#216]
Hello,
autoreboot doesnt work - ESP32, Platformio.

Anybody else have same issue please or i have something wrong?

Thank you

**Comment by dalise** [comment]
Yes I am seeing this also with ESP32, Platform IO

**Comment by ayushsharma82** [comment]
@dalise @petr-novak-digibrocz Can you check if you guys have ElegantOTA.loop() line in loop function of your sketch?

**Comment by dalise** [comment]
Just checked and no, that will do it! 
I think as I referenced the Auto Reboot Doc - https://docs.elegantota.pro/autoreboot/ I neglected to add it in.
thanks!
