### ISSUE TITLE
Use SD card father than Spiffs

### ISSUE THREAD

**Issue by Gregovate** [ayushsharma82/ElegantOTA#231]
My application uses a SD card to store the data so technicians can easily swap out the cards for analysis. I would like to be able to view/delete/update these file OTA and I can't seem to get the file system options to work with it. The Firmware updating is working flawlessly. All files reside on the root of the SD card and I just can't seem to get this to work.

**Comment by ayushsharma82** [comment]
@Gregovate The Filesystem option applies specifically to LittleFS or SPIFFS partitions, which are stored on the MCU's internal flash.

ElegantOTA is designed as a lightweight wrapper around the existing update mechanism. It sounds like you're looking for an SD file browser to view, download, or delete individual files. Feel free to email me at [ayush@softt.io](mailto:ayush@softt.io); we’ve developed an SD file browser library for a client, and we can customize and license it if you’re interested.
