### ISSUE TITLE
update dossier data

### ISSUE THREAD

**Issue by patdarrieulat** [ayushsharma82/ElegantOTA#233]
Bonjour, 
Comment fait on pour update le dossier data , le micrologiciel fonctionne bien , mais pour littlefs on demande un fichier bin

**Comment by patdarrieulat** [comment]
mode OTA   LittleFS/Spiffs  reclame un fichier binaire

**Comment by mathieucarbou** [comment]
Pour créer un .bin de la partition fichier à l'aide de pioarduino ou platformio, mettre les fichier dans le dossier data et exécuter:

`pio run -t buildfq`
`pio run -t uploadfs` 

(La dernière étant pour l'uploader sur l'esp)

**Comment by patdarrieulat** [comment]
merci beaucoup pour la réponse, bonne journée
