### ISSUE TITLE
Any mechanism to check why an upload errors?

### ISSUE THREAD

**Issue by ArsineMan** [ayushsharma82/ElegantOTA#3]
I am receiving an Error on uploading my bin file. I use PlatformIO which creates a .pioenvs/nodemcuv2/firmware.bin file.  After upload attempt I see OTA Failed  Reason -. Just wondering if there is a way for me to see what the error is.

**Comment by ayushsharma82** [comment]
Yeah.. There is currently an error in ElegantOTA Webpage which doesn't show the error. I am working on it and will update the library soon.

**Comment by ayushsharma82** [comment]
Fixed with `v1.1.0`
