### ISSUE TITLE
Source for elegantWebpage.h?

### ISSUE THREAD

**Issue by mike-s123** [ayushsharma82/ElegantOTA#30]
Do you make the source for elegantWebpage.h available? It's hard to work with because it was minified.  I want to be able to change some styles to match the rest of my project. I'd also like to pass the file name chosen by the user, for validity testing (if the user mixes up firmware and filesystem, OTA will happily try to program the wrong thing.) Check like this:

                    int cmd = (filename.indexOf(F(".spiffs.bin")) > -1 ) ? U_SPIFFS : U_FLASH;
                    if (cmd == U_FLASH && !(filename.indexOf(F(".esp32.bin")) > -1) ) {
                      debugMsgln(F("OTA bad filename"),1);
                      return; // wrong image for ESP32
                    }

Even better would be to change the "accept:" on the file-input to reflect which file type the user selects.

**Comment by jnicolson** [comment]
It looks like the source is all in the [UI](https://github.com/ayushsharma82/ElegantOTA/tree/master/ui) directory.  The compress.js file turns it into elegantWebpage.h.

**Comment by mike-s123** [comment]
Thanks.
