### ISSUE TITLE
Progress bar fail with IOS 14.2 

### ISSUE THREAD

**Issue by dagnall53** [ayushsharma82/ElegantOTA#32]
Using IOS (14.2,) the progress bar immediately flashes to 99% on upload.
Presumably this is something Apple breaks, but can you modify the code to be IOS compatible? 
Testing with an older IOS (9.3.6) its worse, and  gets stuck on the ElegantOTA update screen (no choose file tabs etc) and you cannot choose files or update.

**Comment by ayushsharma82** [comment]
This is related to https://github.com/ayushsharma82/AsyncElegantOTA/issues/51

iOS also caches the request which in return makes the progress bar go to 100% directly.

iOS 9.3.6 might not work with modern JS APIs which can cause some problems.
