### ISSUE TITLE
Support for SD card files

### ISSUE THREAD

**Issue by PPKGroup** [ayushsharma82/ElegantOTA#36]
Hi,
I have a ESP32 system with a SD card that utilizes the FS.h.
This works perfectly and serves up 10 odd webpages from the SD card.

I'm having issues doing the following:
1. Firmware OTA updates.
2. General files system updates e.g. update SD card files htm, css, json etc.

How do I do this with the current system or modify the  "AsyncElegantOTA.h" to add this support?

**Comment by ayushsharma82** [comment]
The current system you are proposing is not applicable to the current library, as it's out of the scope of it.

You can follow this tutorial to get a clear picture: https://randomnerdtutorials.com/esp32-ota-over-the-air-arduino/
