### ISSUE TITLE
reload and get an Err_Connection_Timed_Out 

### ISSUE THREAD

**Issue by J4e8a16n** [ayushsharma82/ElegantOTA#38]
Hi,
I am experimenting with ESP32

https://github.com/ayushsharma82/ElegantOTA/blob/master/examples/ESP32_Demo/ESP32_Demo.ino
and I wonder why, after one minute or so, the web page is no more available.

If I press reload the page is reloaded but no more than a minute .
 
After that  if I reload I get an Err_Connection_Timed_Out .

If I reset the ESP32 everything comes back again …. 
Regards,
 
JPD

**Comment by ayushsharma82** [comment]
@J4e8a16n  Hi, Thanks for trying out ElegantOTA.

Please check if any part of your code or library is closing the WebServer?

**Comment by J4e8a16n** [comment]
It seems ....  I resetted the router to  defaults and everything is fine.

**Comment by ayushsharma82** [comment]
Awesome! You may close the issue if it's fixed.
