### ISSUE TITLE
Would be nice if after an update, the option to reboot was made availble

### ISSUE THREAD

**Issue by DanielW0830** [ayushsharma82/ElegantOTA#40]
Most of the time, when I upgrade a device, I would want to reboot after successfully completing the upgrade.
A good idea?   :)

**Comment by ayushsharma82** [comment]
ElegantOTA reboots the device by default. [Reference](https://github.com/ayushsharma82/ElegantOTA/blob/master/src/ElegantOTA.h#L177)
