### ISSUE TITLE
Custom title on update page

### ISSUE THREAD

**Issue by Johboh** [ayushsharma82/ElegantOTA#41]
Hi!
I have several devices locally that runs ElegantOTA, but I always have to think twice that I'm looking at the correct update page for the correct device.
What do you think about showing the hostname on the update page or some other String identifier that can be provided at setup of ElegantOTA?

**Comment by ayushsharma82** [comment]
You can use `setID("ESP-12345")` method to set a custom ID that appears at the bottom of the page.

**Comment by Johboh** [comment]
Oh I didn't know!
Great, thanks 😊
