### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by nelsontechnologies** [ayushsharma82/ElegantOTA#56]
After build for production in UI, what utility do you use to convert to hex to paste into elegantwebpage.h?  In the dist folder, i have favicon, index.html and js.  How do i merge these to the hex?  THank you in advance!

**Comment by rbandres98** [comment]
Hello @nelsontechnologies .
The **elegantWebPage.h** file is automatically updated after use the command `npm run build` inside the **ui folder** of the project. The following is an image with the returned log in console after use this command.
![2021-08-23_17h48_56](https://user-images.githubusercontent.com/29277715/130529383-6312b462-0088-4321-87b5-c6048b399c76.png)

**Comment by ayushsharma82** [comment]
Solution provided by @rbandres98 . Thanks!

Closing ~
