### ISSUE TITLE
CRUSH ...ayushsharma82 / ElegantOTA :(

### ISSUE THREAD

**Issue by Almacubana** [ayushsharma82/ElegantOTA#58]
Hi there!!!
I was really very excited about a month ago when installed the library. BUT... while working perfectly.... after a few uploads the browser became irresponsive. When I plug the ESP8266 on USB on Serial port there is a long error generated followed by a restart. What kind of mistake am I doing? Please Help me!!!

**Comment by ayushsharma82** [comment]
This should be fixed with v2.2.8 - https://github.com/ayushsharma82/ElegantOTA/releases/tag/2.2.8

Please let me know if the issue still persists after updating to v2.2.8
