### ISSUE TITLE
Update stops midway.

### ISSUE THREAD

**Issue by hitenlulla** [ayushsharma82/ElegantOTA#59]
Hello sir, The example code works properly, but when I append that code in my code, the update sticks mid way. Size of my bin file is 3,92,752 bytes. Is there any size limit to use Elegant OTA?

**Comment by ayushsharma82** [comment]
@hitenlulla  No idea, I'll need more information to diagnose it. 

Let me know the following so that I can help you:
- Does it print any error message/exception to `Serial` when it gets stuck?
- Please share your ESP model, board configuration & partition table

**Comment by hitenlulla** [comment]
I am using Hardware Timer in my code to use a dimming circuit. I recently found out that it hinders OTA updates. Do you have any work around?
