### ISSUE TITLE
version 2.2.6 does not show OTA success after upload of new SW version

### ISSUE THREAD

**Issue by dolhastelian** [ayushsharma82/ElegantOTA#67]
![Screenshot from 2021-12-12 17-42-10](https://user-images.githubusercontent.com/3252394/145705982-7c605a25-7648-49f2-bef5-0469a5a03954.png)
The SW is loaded correctly and shows 100% but it does not show the OTA success page

**Comment by dolhastelian** [comment]
![Screenshot from 2021-12-12 17-42-10](https://user-images.githubusercontent.com/3252394/145705976-57c32c74-d0ec-4398-80c4-ea522384b838.png)

**Comment by ayushsharma82** [comment]
@dolhastelian  Can you tell us more about your ESP model and board config?

**Comment by dolhastelian** [comment]
Yes, I tested on esp-01 and Node MCU v2 modules, flashing is successful but not reported in the Web page.

**Comment by ayushsharma82** [comment]
Hi @dolhastelian ,
I've added some fixes in [id-fix](https://github.com/ayushsharma82/ElegantOTA/tree/id-fix) branch, can you please test those out and see if it fixes your issue? You can download that branch and replace it with the existing ElegantOTA folder in your Arduino libraries folder.

**Comment by ayushsharma82** [comment]
This should be fixed with v2.2.8 - https://github.com/ayushsharma82/ElegantOTA/releases/tag/2.2.8

Please let me know if the issue still persists after updating the library.

**Comment by dolhastelian** [comment]
Hello Ayush!,
I tested the latest version and it works!
Can you make an update also for the AsyncElegantOTA ? Thank you.

![image](https://user-images.githubusercontent.com/3252394/147201452-c232ff14-0513-4cee-9040-3d3b8bdfe0b5.png)

**Comment by ArnoldGoat** [comment]
Could we have 2.2.8 installed in VSCode PlatformIO. Latest is 2.2.7 which has the problem described on a Wemos Mini ESP8266. I don't know how to check 2.2.8 as the names don't seem to match (AsyncElegantOTA - ElegantOTA)

**Comment by ayushsharma82** [comment]
Permanently fixed with V3.
