### ISSUE TITLE
Disable Filesystem Upload

### ISSUE THREAD

**Issue by dandud100** [ayushsharma82/ElegantOTA#69]
Hello, is it possible to disable or hide the filesystem update?

I use LittleFS for my projects so this is not useful for me.
Thanks.

**Comment by ayushsharma82** [comment]
Nope, the webpage is pre compiled. By the way it can be used to update
LittleFS too.

**Comment by dandud100** [comment]
How do i define it for LittleFS?

**Comment by rbandres98** [comment]
Hello, @dandud100 . If you want to hide filesystem radio button you have to modify UI project by your way, you can find this at the following line: https://github.com/ayushsharma82/ElegantOTA/blob/master/ui/src/App.vue#L91

**Comment by dandud100** [comment]
> Hello, @dandud100 . If you want to hide filesystem radio button you have to modify UI project by your way, you can find this at the following line: https://github.com/ayushsharma82/ElegantOTA/blob/master/ui/src/App.vue#L91

If I could define elegantota for littlefs it would be useful for me but I don't know how to do this. It is not mentioned anywhere.

**Comment by ayushsharma82** [comment]
This feature is in [ElegantOTA Pro](https://elegantota.pro) now.
