### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by ldijkman** [ayushsharma82/ElegantOTA#70]
Hello
Could it be possible to upload overwrite add a single file to spiffs
Or upload add multiple files without a spiffs bin erase replace
Without erasing other files

Wpuld be usefull to me

https://github.com/ldijkman/randomnerd_esp32_wifi_manager

**Comment by ayushsharma82** [comment]
@ldijkman  Not under scope of ElegantOTA, it's best to create a dedicated file manager for that. ElegantOTA will only facilitate firmware OTA or complete overwrite of LittleFS partition.
