### ISSUE TITLE
Prevent deleting Files in LittleFS Filesystem when uploading OTA

### ISSUE THREAD

**Issue by dandud100** [ayushsharma82/ElegantOTA#71]
How to prevent that the files on the LittleFS gets deleted when uploading an ota?

**Comment by ayushsharma82** [comment]
Hi @dandud100 ,

You can try compiling the binary with the `Erase Flash > Only Sketch` option. Let me know if that keeps the LittleFS contents. 

![image](https://user-images.githubusercontent.com/26592968/150048461-06a12cb8-17ca-420a-a842-ddc006e789fe.png)

**Comment by dandud100** [comment]
> Hi @dandud100 ,
> 
> You can try compiling the binary with the `Erase Flash > Only Sketch` option. Let me know if that keeps the LittleFS contents.
> 
> ![image](https://user-images.githubusercontent.com/26592968/150048461-06a12cb8-17ca-420a-a842-ddc006e789fe.png)

I did this and it erased the littlefs content

**Comment by ayushsharma82** [comment]
Tried on my end. It didn't delete LittleFS partition.
