### ISSUE TITLE
OTA-Update delete WIFI-Data

### ISSUE THREAD

**Issue by KaelanTesseract** [ayushsharma82/ElegantOTA#73]
Hello,

if i make a update with OTA my saved WIFI-Data will be erased. How i can prevend it?

**Comment by t-jones14** [comment]
Does Filesystem AND Firmware OTA upload cause this behavior? Or is it one or the other?

When you have a working & connected copy uploaded to your device, try going to <http://your-device-ip/edit> and save a copy of the **wificred.dat** file in your data folder before your next compile and upload.

![image](https://user-images.githubusercontent.com/40005961/153703191-fd275322-455c-41a8-8e82-99187603c995.png)
