### ISSUE TITLE
Improvement proposal for Readme (installation instructions)

### ISSUE THREAD

**Issue by WolfgangSteininger** [ayushsharma82/ElegantOTA#75]
Hi, 
It might be helpful to document that a partition table needs to be added to the configuration that supports ota.
like its noted: here https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/partition-tables.html

otherwise the upload will fail without a specific message. (at least that happened with my baord)

**Comment by mathieucarbou** [comment]
This is already in the official Expressif doc. Whatever system is used for OTA (Arduino OTA, ElegantOTA or anything else), it requires that the partitions are correctly set. This is unrelated to ow ElegantOTA is working but is related to how the Upload feature works in Expressif.

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/ota.html

> The OTA update mechanism allows a device to update itself based on data received while the normal firmware is running (for example, over Wi-Fi or Bluetooth.)
> 
>OTA requires configuring the [Partition Tables](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/partition-tables.html) of the device with at least two OTA app slot partitions (i.e., ota_0 and ota_1) and an OTA Data Partition.
