### ISSUE TITLE
favIcon

### ISSUE THREAD

**Issue by Skywalkerf34** [ayushsharma82/ElegantOTA#76]
Hi,
I notice that elegantOTA page ask server for favicon.ico every time I load elegantOTA update page
Where is this icon ?

**Comment by t-jones14** [comment]
If you have the "edit.htm.gz" file uploaded, head to "http://<yourdeviceip>/edit" and upload any "favicon.ico" you would like to suppress this error.

**Comment by ayushsharma82** [comment]
Favicon is not necessary, yes the browser will ask for it but you can skip it. The favicon request gets rejected by ESP.
