### ISSUE TITLE
is there any way to run the command on start?

### ISSUE THREAD

**Issue by homonto** [ayushsharma82/ElegantOTA#79]
So I am using this library for all my devices - some sleep, some are always on.
I would like to ask if there is any possibility to catch that OTA started and then i.e. execute the command like:

```
on_OTA_start{
  sleep_enabled = false;
}
```

or so.

Thank you for your great job

**Comment by ayushsharma82** [comment]
Right now ElegantOTA uses the default backend provided by the ESP8266HTTPUpdateServer Arduino library hence not possible to add callbacks right now. 

Callback support in the to-do list. It will be added when the codebase is unique to ElegantOTA.

**Comment by ayushsharma82** [comment]
Added `onStart` and more callbacks with V3 release.
