### ISSUE TITLE
OTA get stuck during upload

### ISSUE THREAD

**Issue by juergmaier** [ayushsharma82/ElegantOTA#80]
I have an ESP-01S module an I have added the ElegantOTA functions to it.
I access the IP address of the device with my browser (Firefox).
Everything looks nice (showing instruction page, executing commands) until I try to upload a new version
The compiled sketch uses 390 KB according to Arduino IDE.
The available space on the ESP-01S shows: ESP.getFreeSketchSpace() 650 KB
The web page updates up to 47% progress, then stops.
In the serial monitor I get this message (with a long stack-dump):

`
ESP.getFreeSketchSpace(); 643072
ERROR[11]: Invalid bootstrapping state, reset ESP8266 before updating

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Exception (29):
epc1=0x4000df64 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

`
I feel I am in a loop?

**Comment by ayushsharma82** [comment]
It should be optimized with V3. Let me know if it happens again.

*Note: If you have flashed ESP through PC and immediately tried ElegantOTA, then make sure to reboot it once. It's a known bug that ESPs won't accept firmware in that case.*
