### ISSUE TITLE
Example of ElegantOTA for Ethernet Port

### ISSUE THREAD

**Issue by simogaspa84** [ayushsharma82/ElegantOTA#81]
Hi @ayushsharma82 .
Thanks for your amazing work.
I would be glad and I think also the community if you can provide an example of using your
OTA lib with the Ethernet instead that with Wifi.
One starting point it could be an integration with this lib which is widely used.

https://github.com/jandrassy/EthernetENC

Thanks for your time

**Comment by ZZKK000** [comment]
refer to:  khoih-prog/AsyncWebServer_ESP32_W5500@^1.6.4, use some AsyncWebServer libarary with ethernet phy.
