### ISSUE TITLE
Does not work with higher port numbers

### ISSUE THREAD

**Issue by brownrb** [ayushsharma82/ElegantOTA#95]
Hi
Dynamic ports are in the range 49152 to 65535 which are available for user applications.

When the server is configured to use a port like 61616, which is a valid port number, ElegantOTA never loads.

If I reconfigure the server to use port 6161 then it works fine. But it is bad practice to use lower number for values. 

Can the code of ElegantOTA be modified to support the dynamic ports? 

Regards
Robert

**Comment by Franck78** [comment]
> When the server is configured to use a port like 61616, which is a valid port number, ElegantOTA never loads.

Hi,
Before saying ElegantOTA never loads, can you say 'any other' apps loads correctly with the dynamic port ?
In other words, have you verified AsyncWebServer is not the problem with a simple page?

If it is an AsyncWebServer problem, then close these report.

thanks
Franck
