### ISSUE TITLE
File upload into existing filesystem (as opposed to uploading/replacing the whole filesystem partition)

### ISSUE THREAD

**Issue by 0x0fe** [ayushsharma82/ElegantOTA#99]
Everything is in the title, what i would like to do is to load an arbitrary file from ElegantOTA, rather than uploading the whole filesystem partition as a bin file.
My understanding is that ElegantOTA does not enforce the type of file, however the underlaying update.h seems to fail when anything else than a firmware or filesystem partition .bin file is provided (well, it will write it, but the filesystem will then be broken since it was not an image of the whole filesystem partition.

In my case lets say i have a configuration fle inside the filesystem and i want to replace it with a new file from Elegant OTA, what would be the right way to do this?

**Comment by simonemarin** [comment]
Hallo I am in the very same situation: got a bunch of web related files (html, css, js) and a json file which holds configuration settings, including which is most crucial the IP of the host. Would be very useful to be able to update only the web related files and not the configuration json file, in my case that file can be edited with the web interface itself so the editing is lost whenever I upload the .bin with the file system.
